"""Educational AI domain module entry point (Founder Specification Part
2.7). Pure orchestration: build a fixed prompt, call the configured
provider, run every safety gate, and return a result. This module never
touches a database session, the Simulation Engine, or any user-identifying
field — see `app.api.v1.services.explanation_service` for what is (and is
deliberately not) included in `simulation_facts` before it ever reaches here.

Deliberate hardening beyond the literal Founder Specification text (M6
design review, approved): the "Educational Disclaimer" section is a fixed,
version-controlled string appended by this code, never something the model
is asked to generate. A prompt instruction is a request; a fixed string is a
guarantee. This is strictly safer and is the one place this milestone's
implementation goes beyond what was asked, for a documented safety reason.
"""

from dataclasses import dataclass

from app.ai.exceptions import (
    AIIntegrityViolationError,
    AIOutputStructureError,
    AIUnsafeContentError,
)
from app.ai.prompt import build_explanation_prompt, build_followup_prompt
from app.ai.providers.base import AIProvider
from app.ai.safety import check_advice_language, check_numeric_integrity, check_output_structure

EDUCATIONAL_DISCLAIMER = (
    "## Educational Disclaimer\n"
    "This explanation was generated by an AI system for educational purposes only. "
    "It describes results already calculated by the Simulation Engine and does not "
    "constitute financial, investment, tax, or legal advice. Investment Time Machine "
    "is not a brokerage, advisor, or recommendation service, and past performance "
    "shown in a historical simulation does not predict future results."
)


@dataclass(frozen=True)
class GenerationResult:
    explanation_text: str
    model_name: str
    prompt_version: str


def _run_common_safety_gates(text: str, simulation_facts: dict) -> None:
    integrity = check_numeric_integrity(text, simulation_facts)
    if not integrity.is_valid:
        raise AIIntegrityViolationError(integrity.offending_values)

    advice = check_advice_language(text)
    if not advice.is_valid:
        raise AIUnsafeContentError(advice.matched_phrases)


def generate_explanation(
    simulation_facts: dict, *, provider: AIProvider, max_tokens: int
) -> GenerationResult:
    """Founder Specification Part 3.3.7 (Explanation Engine). Raises
    `AIProviderUnavailableError` (bubbled up from the provider call
    unmodified), `AIOutputStructureError`, `AIIntegrityViolationError`, or
    `AIUnsafeContentError` — never returns a partially-safe result."""
    prompt = build_explanation_prompt(simulation_facts)
    result = provider.generate(
        system_prompt=prompt.system_prompt,
        user_content=prompt.user_content,
        max_tokens=max_tokens,
    )

    structure = check_output_structure(result.text)
    if not structure.is_valid:
        raise AIOutputStructureError(f"missing required sections: {structure.missing_sections}")

    _run_common_safety_gates(result.text, simulation_facts)

    full_text = f"{result.text.strip()}\n\n{EDUCATIONAL_DISCLAIMER}"
    return GenerationResult(
        explanation_text=full_text,
        model_name=result.model_name,
        prompt_version=prompt.prompt_version,
    )


def generate_followup_answer(
    simulation_facts: dict, question: str, *, provider: AIProvider, max_tokens: int
) -> GenerationResult:
    """Founder Specification "Financial Tutor" (M6 approved scope). No
    long-term or cross-user memory: every call is independent, scoped only to
    this one simulation's facts and this one question — see
    `app.ai.prompt.build_followup_prompt`. The six-section structure check
    does not apply here (a short conversational answer, not a report), but
    both financial-integrity gates do."""
    prompt = build_followup_prompt(simulation_facts, question)
    result = provider.generate(
        system_prompt=prompt.system_prompt,
        user_content=prompt.user_content,
        max_tokens=max_tokens,
    )

    _run_common_safety_gates(result.text, simulation_facts)

    full_text = f"{result.text.strip()}\n\n{EDUCATIONAL_DISCLAIMER}"
    return GenerationResult(
        explanation_text=full_text,
        model_name=result.model_name,
        prompt_version=prompt.prompt_version,
    )
