import uuid
from typing import TYPE_CHECKING

from sqlalchemy import ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin, pg_enum
from app.models.enums import AIGenerationStatus

if TYPE_CHECKING:
    from app.models.simulation import Simulation


class AIExplanation(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Educational content generated by the AI Intelligence Service. Strictly
    supplemental: simulation results are financial truth, this table is never
    treated as financial data (Founder Specification Part 2.6.26).

    explanation_text is nullable for the same reason Simulation's output
    columns are nullable: AIGenerationStatus.PENDING/FAILED are valid states
    with no text yet. simulation_id is NOT NULL — every explanation belongs to
    exactly one simulation.
    """

    __tablename__ = "ai_explanations"

    simulation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("simulations.id"), nullable=False
    )
    prompt_version: Mapped[str] = mapped_column(String(20), nullable=False)
    model_name: Mapped[str] = mapped_column(String(100), nullable=False)
    input_summary: Mapped[dict] = mapped_column(JSONB, nullable=False)
    explanation_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    generation_status: Mapped[AIGenerationStatus] = mapped_column(
        pg_enum(AIGenerationStatus, "ai_generation_status_enum"),
        nullable=False,
        server_default=AIGenerationStatus.PENDING.value,
    )
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    simulation: Mapped["Simulation"] = relationship(back_populates="ai_explanations")

    def __repr__(self) -> str:
        return (
            f"AIExplanation(simulation_id={self.simulation_id!r}, "
            f"status={self.generation_status!r})"
        )
